version: "3.8"
services:

  app:
    build:
      context: ./docker/php
    restart: always
    volumes:
      - .:/app
    ports:
      - 8080:8000
    depends_on:
      - db
      - redis

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: secret

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data



  

volumes:
  db_data:
  redis_data:
